name: Tests

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Task00
        run: |
          my_tests/tester.sh 00